import{i as l,S as h}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const c="/goit-js-hw-12/assets/error-74a0cd69.svg",y=document.querySelector(".gallery"),b=document.querySelector(".form");let a;function L(s){if(!s.hits.length){l.error({theme:"dark",position:"topRight",progressBarColor:"rgb(181, 27, 27)",backgroundColor:"rgb(239, 64, 64)",iconUrl:c,message:"Sorry, there are no images matching your search query. Please try again!"}),m();return}const o=s.hits.map(n=>{const{webformatURL:e,largeImageURL:t,tags:i,likes:d,views:g,comments:p,downloads:f}=n;return`<li class="gallery-item hidden">
          <a class="gallery-link" href="${t}">
            <img
              class="gallery-image"
              src="${e}"
              alt="${i}"
            />
            <div class="img-descr-container">
              <p class="img-descr-subtitle">Likes<span class="img-descr-qty">${d}</span></p>
              <p class="img-descr-subtitle">Views<span class="img-descr-qty">${g}</span></p>
              <p class="img-descr-subtitle">Comments<span class="img-descr-qty">${p}</span></p>
              <p class="img-descr-subtitle">Downloads<span class="img-descr-qty">${f}</span></p>
            </div>
          </a>
        </li>`}).join("");y.innerHTML=o,document.querySelectorAll(".gallery-item").forEach((n,e)=>{setTimeout(()=>{n.classList.remove("hidden"),n.classList.add("fade-in")},e*100)}),a?a.refresh():(a=new h(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt",scrollZoom:!1}),a.on("error.simplelightbox",function(n){console.log(n)})),b.reset()}function S(s){const o="https://pixabay.com/api",r=new URLSearchParams({key:"43998690-c32ec46c3205eb1d30dd41df5",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0});return`${o}?${r}`}function q(s){const o=S(s);fetch(o,{referrerPolicy:"unsafe-url"}).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()}).then(r=>L(r)).catch(r=>{console.log("Error fetching photos:",r),l.error({theme:"dark",position:"topRight",progressBarColor:"rgb(181, 27, 27)",backgroundColor:"rgb(239, 64, 64)",iconUrl:c,message:r.message})}).finally(()=>m())}const w=document.querySelector(".form"),$=document.querySelector(".gallery"),u=document.querySelector(".loader");function v(){u.style.display="block"}function m(){u.style.display="none"}function P(s){s.preventDefault();const o=s.target;if(o.elements.input.value.trim()===""){l.warning({theme:"dark",position:"topRight",message:"Input is empty",backgroundColor:"rgb(255, 150, 0)",progressBarColor:"rgb(180, 70, 0)"});return}const r=o.elements.input.value.trim();$.innerHTML="",v(),q(r)}w.addEventListener("submit",P);
//# sourceMappingURL=commonHelpers.js.map
